### ISSUE TITLE
Read token from cache

### ISSUE THREAD

**Issue by kiblik** [dkyanakiev/vaul7y#19]
**Is your feature request related to a problem? Please describe what it is.**
The necessity to copy and paste tokens after `vault login` is a friction point. The reading from the vault cache would be beneficial. 

**Describe the solution you'd like**
Official [documentation](https://developer.hashicorp.com/vault/docs/commands#authenticating-to-vault
) describes
> The CLI uses a token helper to cache access tokens after authenticating with vault login
> The default file for cached tokens is `~/.vault-token` ...

It would be nice if `vaul7y` would be able to use this location for fetching tokens.

**Additional context**
Currently, the token can be stored in a config file or loaded from EnvVar `VAULT_TOKEN`. An additional method would be nice.

**Comment by dkyanakiev** [comment]
Thanks @kiblik 
Thats a nice suggestion, was simply looking at this from my usual workflows and how I usually interact with the clusters.
Should be a fairly quick addition!

**Comment by dkyanakiev** [comment]
Started looking and testing this but there are a few things I'm not entirely happy with. 
The default token in `~/.vault-token`  could be stale and could break the auth workflow.
A good compromise would be to allow the CLI to use the cache if we provide a flag.
`vaul7y --cache` or something of the sort.
Or alternatively look for tokens in the following order
1. Local cache
2. Config file
3. Env variable 
But obviously this could be an issue if you have stale token in either location but I guess that's always an issue/risk. 
What do you think?

**Comment by kiblik** [comment]
I'm not sure how many different methods the original `vault` binary supports, but in the scope that `vaul7y` uses as well, I would follow the same order as `vault` uses. If a stale token in the cache is breaking the workflow, it will break the same workflow for `vault` as well. So I suppose it is fine, and the user needs to investigate why both `vault` and `vaul7y` are behaving differently than they expect.

So ^ this says in which order "local cache" and "env var" should be evaluated. The location of the "config file" is still open question.
I would probably put it first (even override the cache). If use want to use a different configuration in `vaul7y` (compared to other tools) it should be accepted and preferred.

**Comment by dkyanakiev** [comment]
0.1.9 has the update for this. 
Closing the issue, feel free to reopen if you notice anything wrong with it.

**Comment by kiblik** [comment]
Thank you @dkyanakiev.
I was thinking about `config file > cached token > env variables` but this is good for me as well.
I have tested implementation with cache and it works.
